services:
  beehive:
    container_name: beehive
    image: beehive
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      BEEKEEPER_API_URL: ${BEEKEEPER_API_URL:-https://beekeeper.login.no/api}
      NEXT_PUBLIC_BEEKEEPER_WSS_URL: ${NEXT_PUBLIC_BEEKEEPER_WSS_URL:-wss://beekeeper.login.no/api}
    networks:
      - workerbee_default
      - tekkom_bot_default
      - beekeeper_default
    mem_limit: 2g
    cpus: "2.0"

networks:
  workerbee_default:
    external: true
  tekkom_bot_default:
    external: true
  beekeeper_default:
    external: true
